### ISSUE TITLE
Deserves to die

### ISSUE THREAD

**Issue by brys0** [bizojs/phone#1]
This project is awful and doesn't work 💀

**Comment by br4dw** [comment]
respectfully, go fuck yourself

**Comment by brys0** [comment]
Reopen cuz ur bozo + ratio and src is still here 😭

**Comment by br4dw** [comment]
![hmm](https://i.ytimg.com/vi/C_1V_tGrtlw/maxresdefault.jpg)

**Comment by brys0** [comment]
When will you remove the source code???

**Comment by brys0** [comment]
day 284 of waiting for source code to be removed...
